interface Env { ASSETS: Fetcher; DB: D1Database; UPLOADS: R2Bucket }
const defaults = { brand:"Rainbow Birthday Card", intro:"JOIN US AS WE THROW JANE<br>A VERY SPECIAL<br>3RD BIRTHDAY PARTY", headline:"young,<br>wild &<br>three", photoPlaceholder:"上传一张主角照片<br>它会显示在这里", date:"FRIDAY, AUGUST 24TH", time:"AT 4 P.M.", place:"OUR PLACE", saveButton:"保存文字", uploadButton:"上传照片", statusHint:"点击文字即可修改，保存后公网也会更新。", wishFormTitle:"给朋友发祝福", wishFormNote:"把这张卡发出去，大家写下的祝福会一起留在这里。", wishButton:"发送祝福", wishListTitle:"祝福留言" };
let initialized = false;
async function init(db:D1Database) { if(initialized)return; await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS wishes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)")]); initialized=true }
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const clean=(v:unknown,max:number)=>String(v||"").replace(/\s+/g," ").trim().slice(0,max);
const cleanHtml=(v:unknown,max:number)=>String(v||"").replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi,"").replace(/\son\w+=(?:\"[^\"]*\"|'[^']*')/gi,"").trim().slice(0,max);
async function api(request:Request,env:Env,url:URL):Promise<Response|null>{
  if(!url.pathname.startsWith("/api/"))return null; await init(env.DB);
  if(url.pathname==="/api/wishes"&&request.method==="GET"){const rows=await env.DB.prepare("SELECT id,name,message,created_at AS createdAt FROM wishes ORDER BY id DESC LIMIT 100").all();return json(rows.results)}
  if(url.pathname==="/api/wishes"&&request.method==="POST"){const input=await request.json() as Record<string,unknown>;const name=clean(input.name,40),message=clean(input.message,500);if(!name||!message)return json({error:"name_and_message_required"},400);await env.DB.prepare("INSERT INTO wishes (name,message,created_at) VALUES (?,?,?)").bind(name,message,new Date().toISOString()).run();return json({ok:true})}
  if(url.pathname==="/api/card6/settings"&&request.method==="GET"){const rows=await env.DB.prepare("SELECT key,value FROM settings").all<{key:string,value:string}>();const saved=Object.fromEntries(rows.results.map(r=>[r.key,r.value]));const photo=await env.UPLOADS.head("card6-photo");return json({...defaults,...saved,...(photo?{photoUpdatedAt:photo.uploaded.toISOString()}:{})})}
  if(url.pathname==="/api/card6/settings"&&request.method==="POST"){const input=await request.json() as Record<string,unknown>;await env.DB.batch(Object.keys(defaults).map(key=>env.DB.prepare("INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,cleanHtml(input[key]||defaults[key as keyof typeof defaults],900))));return json({ok:true})}
  if(url.pathname==="/api/card6/photo"&&(request.method==="GET"||request.method==="HEAD")){const object=await env.UPLOADS.get("card6-photo");if(!object)return new Response("Not found",{status:404});return new Response(request.method==="HEAD"?null:object.body,{headers:{"content-type":object.httpMetadata?.contentType||"image/jpeg","cache-control":"no-store"}})}
  if(url.pathname==="/api/card6/photo"&&request.method==="POST"){const input=await request.json() as {image?:string};const match=String(input.image||"").match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)return json({error:"invalid_image"},400);const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));if(!bytes.length||bytes.length>5_000_000)return json({error:"image_too_large"},400);await env.UPLOADS.put("card6-photo",bytes,{httpMetadata:{contentType:match[1]}});return json({ok:true,photoUpdatedAt:new Date().toISOString()})}
  return json({error:"not_found"},404)
}
export default {async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);const response=await api(request,env,url);if(response)return response;const routes:Record<string,string>={"/":"/index.html"};for(let i=2;i<=6;i++){routes[`/card${i}`]=`/card${i}/index.html`;routes[`/card${i}/`]=`/card${i}/index.html`}if(routes[url.pathname])url.pathname=routes[url.pathname];return env.ASSETS.fetch(new Request(url,request))}};
